### PR TITLE
Remove procket and use unix domain socket in erlang 19.0-rc2

### PR DESCRIPTION
**Pull request by saa**

### CODE REVIEW

**Comment by jeanparpaillon** [comment]
Thanks for your pr.
Build fails on a warning:
src/dbus_transport_unix.erl:52: variable 'Mode' is unused

**Comment by saa** [comment]
Hm, I will fix today.

**Comment by saa** [comment]
Compile is ok, but tests failed also as for me. Interesting.

**Comment by saa** [comment]
@jeanparpaillon can you run tests on this branch on your env?

**Comment by jeanparpaillon** [comment]
The pr fails because of erlang 19 not available on travis
Can you add a script to test the pr with erlang 19 on travis ? Using kerl would probable be the best choice

**Comment by slashmili** [comment]
Well I'm not sure why do you say Travis doesn't support Erlang 19 because essentially it uses `kerl`. and as you can see in this build that I just ran https://travis-ci.org/slashmili/erlang-dbus/builds/161296209 (from my own fork) it's using Erlang 19:

```
...
$ erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell
"19"
...
```

I also tried it in my machine with Erlang `19.0.2` and it failed.

**Comment by jeanparpaillon** [comment]
Last time I've checked, erlang 19 was not supported on this page: https://docs.travis-ci.com/user/languages/erlang
It may have changed, hopefully :)
Anyway, there may be other issues on this pull request. Feel free to contribute, (re)code ...

**Pull request closed without merging**
