### PR TITLE
Unix domain socket implementation 

### PR DESCRIPTION
**Pull request by slashmili**
So this PR is based on #23 plus fixes for test and including Erlang 19.0 to the build list.

There is one slight problem which I couldn't figure out and it's when I use 

```
{ok, Bus} = dbus_bus_connection:connect(session)
```

The problem is that the socket is create for a user session is `abstract address` it's something like :
```
unix:abstract=/tmp/dbus-cNsBK4GIj1
```

I'm waiting for an answer in erlang/otp/pull/612 to find out how to deal with connection to abstract address

### CODE REVIEW

**Comment by slashmili** [comment]
Ok I figured it out how to handle abstract socket now it works

```
iex(2)> Service = "net.lizenn.dbus.SampleService"
"net.lizenn.dbus.SampleService"
iex(3)> Iface =   "net.lizenn.dbus.SampleInterface"
"net.lizenn.dbus.SampleInterface"
iex(4)> {:ok, bus} = :dbus_bus_connection.connect(:session)

16:21:52.975 [info]  Connecting to UNIX socket: <<0, 47, 116, 109, 112, 47, 100, 98, 117, 115, 45, 99, 78, 115, 66, 75, 52, 71,
  73, 106, 49>>


16:21:52.976 [info]  DBUS auth: sending initial data


16:21:52.977 [info]  Got GUID '329be89f343c5e4df8265df757e24750' from the server


16:21:52.977 [info]  Succesfully negotiated UNIX FD passing


16:21:52.977 [info]  Calling "/"::"org.freedesktop.DBus".:Hello([])


16:21:52.988 [info]  Hello connection id: ":1.104"

{:ok, {:dbus_bus_connection, #PID<0.158.0>}}
iex(5)> {ok, o} = :dbus_proxy.start_link(bus, service, "/root")

16:21:52.988 [info]  Introspecting: "net.lizenn.dbus.SampleService":"/root"

{:ok, #PID<0.160.0>}
iex(6)> n = 10
10
iex(7)> bin = :binary.copy("x", n)
"xxxxxxxxxx"
iex(8)> :dbus_proxy.call(o, iface, "GetString", [n])

16:21:53.537 [info]  Calling "/root":"net.lizenn.dbus.SampleInterface"."GetString"('\n')

{:ok, "xxxxxxxxxx"}
```

@jeanparpaillon please check the code and give me feedback

**Comment by jeanparpaillon** [comment]
great, thank you for your contrib !

**Comment by slashmili** [comment]
@jeanparpaillon Thanks for accepting it 🎉 

Could you also update the package in hex?

**Comment by slashmili** [comment]
hey @jeanparpaillon just want do a quick check, can you publish it in hex please?


Thanks

**Comment by jeanparpaillon** [comment]
Sorry, but I have troubles uploading right now. Either hex.pm is broken or rebar3 hex plugin...
Let me check

**Comment by slashmili** [comment]
@jeanparpaillon if you grant me access to the package in hex, I can work on it. You can usually find me in freenode under username `milad`

**Comment by jeanparpaillon** [comment]
@slashmili Thanks for your proposal. Unfortunately, I'm currently not the maintainer of dbus package on hex.pm. I'm actually in touch with hex.pm to take over the ownership as the maintainer is unreachable. As soon as I have the ownership, I can add you as co-maintainer.

**Pull request merged**
