### PR TITLE
Fixed Project Name Conflict on Hex.pm

### PR DESCRIPTION
**Pull request by ffringel**
Fixed project name conflict on hex.pm and added image link in README.md to the project

### CODE REVIEW

**Comment by jeanparpaillon** [comment]
I suppose you've forgotten to rebase since I've accepted the pr.

Then, we need to think about another solution, because, even if if works, technically, this app is already used in other projects (which should be updated) + the 'dbus' name has been chosen on purpose since D-Bus is a well known protocol.

-> let me contact https://github.com/aforward/dbus author

**Comment by ffringel** [comment]
Ok. So, I suppose we wait for @aforward to change the name of his app then?

**Comment by jeanparpaillon** [comment]
Would be nice, yes.

Wait & see :)

**Comment by jeanparpaillon** [comment]
https://github.com/aforward/sadbus project has been renamed. There's no need for this pr anymore.

**Comment by ffringel** [comment]
Great. I'm just waiting on him to give me add authority, so I can override the dbus on Hex.pm

**Comment by ffringel** [comment]
Great. I'm just waiting on him to give me add authority, so I can override the dbus on Hex.pm

**Pull request closed without merging**
